//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 03:37:10 PM MSK 
//


package ru.demo.pnpscada.soap.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for activeKeyValueVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="activeKeyValueVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codeGen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="newPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numFreeAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="servicePass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "activeKeyValueVO", propOrder = {
    "codeGen",
    "isActive",
    "newPolicy",
    "numFreeAccount",
    "servicePass"
})
public class ActiveKeyValueVO {

    protected String codeGen;
    protected Boolean isActive;
    protected String newPolicy;
    protected String numFreeAccount;
    protected String servicePass;

    /**
     * Gets the value of the codeGen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeGen() {
        return codeGen;
    }

    /**
     * Sets the value of the codeGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeGen(String value) {
        this.codeGen = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsActive(Boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the newPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewPolicy() {
        return newPolicy;
    }

    /**
     * Sets the value of the newPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewPolicy(String value) {
        this.newPolicy = value;
    }

    /**
     * Gets the value of the numFreeAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumFreeAccount() {
        return numFreeAccount;
    }

    /**
     * Sets the value of the numFreeAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumFreeAccount(String value) {
        this.numFreeAccount = value;
    }

    /**
     * Gets the value of the servicePass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicePass() {
        return servicePass;
    }

    /**
     * Sets the value of the servicePass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicePass(String value) {
        this.servicePass = value;
    }

}
