//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 03:37:10 PM MSK 
//


package ru.demo.pnpscada.soap.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.demo.pnpscada.soap.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ActiveKeyProNew_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKeyProNew");
    private final static QName _ActiveKeyProNewResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKeyProNewResponse");
    private final static QName _UpdatePointOfCustomer_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updatePointOfCustomer");
    private final static QName _UpdatePointOfCustomerResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updatePointOfCustomerResponse");
    private final static QName _GetDateDatabase_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getDateDatabase");
    private final static QName _GetDateDatabaseResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getDateDatabaseResponse");
    private final static QName _UpdateSyncHourBranch_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updateSyncHourBranch");
    private final static QName _UpdateSyncHourBranchResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updateSyncHourBranchResponse");
    private final static QName _UpdateTotalPointOfSwapCustomer_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updateTotalPointOfSwapCustomer");
    private final static QName _UpdateTotalPointOfSwapCustomerResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updateTotalPointOfSwapCustomerResponse");
    private final static QName _ActiveKeyPro_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKeyPro");
    private final static QName _ActiveKeyProResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKeyProResponse");
    private final static QName _CountTransaction_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "countTransaction");
    private final static QName _CountTransactionResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "countTransactionResponse");
    private final static QName _GetNumRowConfigPos_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getNumRowConfigPos");
    private final static QName _GetNumRowConfigPosResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getNumRowConfigPosResponse");
    private final static QName _CheckCodeBranch_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "checkCodeBranch");
    private final static QName _CheckCodeBranchResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "checkCodeBranchResponse");
    private final static QName _GetNumRowConfig_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getNumRowConfig");
    private final static QName _GetNumRowConfigResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getNumRowConfigResponse");
    private final static QName _ActiveKeyNew_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKeyNew");
    private final static QName _ActiveKeyNewResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKeyNewResponse");
    private final static QName _GetLicenseKeyByShortKey_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getLicenseKeyByShortKey");
    private final static QName _GetLicenseKeyByShortKeyResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getLicenseKeyByShortKeyResponse");
    private final static QName _CountCategory_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "countCategory");
    private final static QName _CountCategoryResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "countCategoryResponse");
    private final static QName _GetPointOfCustomer_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getPointOfCustomer");
    private final static QName _GetPointOfCustomerResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getPointOfCustomerResponse");
    private final static QName _GetLicenseKey_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getLicenseKey");
    private final static QName _GetLicenseKeyResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "getLicenseKeyResponse");
    private final static QName _CheckSyncShop_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "checkSyncShop");
    private final static QName _CheckSyncShopResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "checkSyncShopResponse");
    private final static QName _UpdateCodeBranch_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updateCodeBranch");
    private final static QName _UpdateCodeBranchResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updateCodeBranchResponse");
    private final static QName _UpdatePointOfSwapCustomer_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updatePointOfSwapCustomer");
    private final static QName _UpdatePointOfSwapCustomerResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "updatePointOfSwapCustomerResponse");
    private final static QName _ActiveKey_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKey");
    private final static QName _ActiveKeyResponse_QNAME = new QName("http://service.client.pos.shopy.viettel.com/", "activeKeyResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.demo.pnpscada.soap.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActiveKeyProNew }
     * 
     */
    public ActiveKeyProNew createActiveKeyProNew() {
        return new ActiveKeyProNew();
    }

    /**
     * Create an instance of {@link ActiveKeyProNewResponse }
     * 
     */
    public ActiveKeyProNewResponse createActiveKeyProNewResponse() {
        return new ActiveKeyProNewResponse();
    }

    /**
     * Create an instance of {@link UpdatePointOfCustomer }
     * 
     */
    public UpdatePointOfCustomer createUpdatePointOfCustomer() {
        return new UpdatePointOfCustomer();
    }

    /**
     * Create an instance of {@link UpdatePointOfCustomerResponse }
     * 
     */
    public UpdatePointOfCustomerResponse createUpdatePointOfCustomerResponse() {
        return new UpdatePointOfCustomerResponse();
    }

    /**
     * Create an instance of {@link GetDateDatabase }
     * 
     */
    public GetDateDatabase createGetDateDatabase() {
        return new GetDateDatabase();
    }

    /**
     * Create an instance of {@link GetDateDatabaseResponse }
     * 
     */
    public GetDateDatabaseResponse createGetDateDatabaseResponse() {
        return new GetDateDatabaseResponse();
    }

    /**
     * Create an instance of {@link UpdateSyncHourBranch }
     * 
     */
    public UpdateSyncHourBranch createUpdateSyncHourBranch() {
        return new UpdateSyncHourBranch();
    }

    /**
     * Create an instance of {@link UpdateSyncHourBranchResponse }
     * 
     */
    public UpdateSyncHourBranchResponse createUpdateSyncHourBranchResponse() {
        return new UpdateSyncHourBranchResponse();
    }

    /**
     * Create an instance of {@link UpdateTotalPointOfSwapCustomer }
     * 
     */
    public UpdateTotalPointOfSwapCustomer createUpdateTotalPointOfSwapCustomer() {
        return new UpdateTotalPointOfSwapCustomer();
    }

    /**
     * Create an instance of {@link UpdateTotalPointOfSwapCustomerResponse }
     * 
     */
    public UpdateTotalPointOfSwapCustomerResponse createUpdateTotalPointOfSwapCustomerResponse() {
        return new UpdateTotalPointOfSwapCustomerResponse();
    }

    /**
     * Create an instance of {@link ActiveKeyPro }
     * 
     */
    public ActiveKeyPro createActiveKeyPro() {
        return new ActiveKeyPro();
    }

    /**
     * Create an instance of {@link ActiveKeyProResponse }
     * 
     */
    public ActiveKeyProResponse createActiveKeyProResponse() {
        return new ActiveKeyProResponse();
    }

    /**
     * Create an instance of {@link CountTransaction }
     * 
     */
    public CountTransaction createCountTransaction() {
        return new CountTransaction();
    }

    /**
     * Create an instance of {@link CountTransactionResponse }
     * 
     */
    public CountTransactionResponse createCountTransactionResponse() {
        return new CountTransactionResponse();
    }

    /**
     * Create an instance of {@link GetNumRowConfigPos }
     * 
     */
    public GetNumRowConfigPos createGetNumRowConfigPos() {
        return new GetNumRowConfigPos();
    }

    /**
     * Create an instance of {@link GetNumRowConfigPosResponse }
     * 
     */
    public GetNumRowConfigPosResponse createGetNumRowConfigPosResponse() {
        return new GetNumRowConfigPosResponse();
    }

    /**
     * Create an instance of {@link CheckCodeBranch }
     * 
     */
    public CheckCodeBranch createCheckCodeBranch() {
        return new CheckCodeBranch();
    }

    /**
     * Create an instance of {@link CheckCodeBranchResponse }
     * 
     */
    public CheckCodeBranchResponse createCheckCodeBranchResponse() {
        return new CheckCodeBranchResponse();
    }

    /**
     * Create an instance of {@link GetNumRowConfig }
     * 
     */
    public GetNumRowConfig createGetNumRowConfig() {
        return new GetNumRowConfig();
    }

    /**
     * Create an instance of {@link GetNumRowConfigResponse }
     * 
     */
    public GetNumRowConfigResponse createGetNumRowConfigResponse() {
        return new GetNumRowConfigResponse();
    }

    /**
     * Create an instance of {@link ActiveKeyNew }
     * 
     */
    public ActiveKeyNew createActiveKeyNew() {
        return new ActiveKeyNew();
    }

    /**
     * Create an instance of {@link ActiveKeyNewResponse }
     * 
     */
    public ActiveKeyNewResponse createActiveKeyNewResponse() {
        return new ActiveKeyNewResponse();
    }

    /**
     * Create an instance of {@link GetLicenseKeyByShortKey }
     * 
     */
    public GetLicenseKeyByShortKey createGetLicenseKeyByShortKey() {
        return new GetLicenseKeyByShortKey();
    }

    /**
     * Create an instance of {@link GetLicenseKeyByShortKeyResponse }
     * 
     */
    public GetLicenseKeyByShortKeyResponse createGetLicenseKeyByShortKeyResponse() {
        return new GetLicenseKeyByShortKeyResponse();
    }

    /**
     * Create an instance of {@link CountCategory }
     * 
     */
    public CountCategory createCountCategory() {
        return new CountCategory();
    }

    /**
     * Create an instance of {@link CountCategoryResponse }
     * 
     */
    public CountCategoryResponse createCountCategoryResponse() {
        return new CountCategoryResponse();
    }

    /**
     * Create an instance of {@link GetPointOfCustomer }
     * 
     */
    public GetPointOfCustomer createGetPointOfCustomer() {
        return new GetPointOfCustomer();
    }

    /**
     * Create an instance of {@link GetPointOfCustomerResponse }
     * 
     */
    public GetPointOfCustomerResponse createGetPointOfCustomerResponse() {
        return new GetPointOfCustomerResponse();
    }

    /**
     * Create an instance of {@link GetLicenseKey }
     * 
     */
    public GetLicenseKey createGetLicenseKey() {
        return new GetLicenseKey();
    }

    /**
     * Create an instance of {@link GetLicenseKeyResponse }
     * 
     */
    public GetLicenseKeyResponse createGetLicenseKeyResponse() {
        return new GetLicenseKeyResponse();
    }

    /**
     * Create an instance of {@link CheckSyncShop }
     * 
     */
    public CheckSyncShop createCheckSyncShop() {
        return new CheckSyncShop();
    }

    /**
     * Create an instance of {@link CheckSyncShopResponse }
     * 
     */
    public CheckSyncShopResponse createCheckSyncShopResponse() {
        return new CheckSyncShopResponse();
    }

    /**
     * Create an instance of {@link UpdateCodeBranch }
     * 
     */
    public UpdateCodeBranch createUpdateCodeBranch() {
        return new UpdateCodeBranch();
    }

    /**
     * Create an instance of {@link UpdateCodeBranchResponse }
     * 
     */
    public UpdateCodeBranchResponse createUpdateCodeBranchResponse() {
        return new UpdateCodeBranchResponse();
    }

    /**
     * Create an instance of {@link UpdatePointOfSwapCustomer }
     * 
     */
    public UpdatePointOfSwapCustomer createUpdatePointOfSwapCustomer() {
        return new UpdatePointOfSwapCustomer();
    }

    /**
     * Create an instance of {@link UpdatePointOfSwapCustomerResponse }
     * 
     */
    public UpdatePointOfSwapCustomerResponse createUpdatePointOfSwapCustomerResponse() {
        return new UpdatePointOfSwapCustomerResponse();
    }

    /**
     * Create an instance of {@link ActiveKey }
     * 
     */
    public ActiveKey createActiveKey() {
        return new ActiveKey();
    }

    /**
     * Create an instance of {@link ActiveKeyResponse }
     * 
     */
    public ActiveKeyResponse createActiveKeyResponse() {
        return new ActiveKeyResponse();
    }

    /**
     * Create an instance of {@link ActiveKeyValueVO }
     * 
     */
    public ActiveKeyValueVO createActiveKeyValueVO() {
        return new ActiveKeyValueVO();
    }

    /**
     * Create an instance of {@link CheckCodeVO }
     * 
     */
    public CheckCodeVO createCheckCodeVO() {
        return new CheckCodeVO();
    }

    /**
     * Create an instance of {@link CustomersVO }
     * 
     */
    public CustomersVO createCustomersVO() {
        return new CustomersVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKeyProNew }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKeyProNew }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKeyProNew")
    public JAXBElement<ActiveKeyProNew> createActiveKeyProNew(ActiveKeyProNew value) {
        return new JAXBElement<ActiveKeyProNew>(_ActiveKeyProNew_QNAME, ActiveKeyProNew.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKeyProNewResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKeyProNewResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKeyProNewResponse")
    public JAXBElement<ActiveKeyProNewResponse> createActiveKeyProNewResponse(ActiveKeyProNewResponse value) {
        return new JAXBElement<ActiveKeyProNewResponse>(_ActiveKeyProNewResponse_QNAME, ActiveKeyProNewResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePointOfCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdatePointOfCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updatePointOfCustomer")
    public JAXBElement<UpdatePointOfCustomer> createUpdatePointOfCustomer(UpdatePointOfCustomer value) {
        return new JAXBElement<UpdatePointOfCustomer>(_UpdatePointOfCustomer_QNAME, UpdatePointOfCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePointOfCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdatePointOfCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updatePointOfCustomerResponse")
    public JAXBElement<UpdatePointOfCustomerResponse> createUpdatePointOfCustomerResponse(UpdatePointOfCustomerResponse value) {
        return new JAXBElement<UpdatePointOfCustomerResponse>(_UpdatePointOfCustomerResponse_QNAME, UpdatePointOfCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDateDatabase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetDateDatabase }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getDateDatabase")
    public JAXBElement<GetDateDatabase> createGetDateDatabase(GetDateDatabase value) {
        return new JAXBElement<GetDateDatabase>(_GetDateDatabase_QNAME, GetDateDatabase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDateDatabaseResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetDateDatabaseResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getDateDatabaseResponse")
    public JAXBElement<GetDateDatabaseResponse> createGetDateDatabaseResponse(GetDateDatabaseResponse value) {
        return new JAXBElement<GetDateDatabaseResponse>(_GetDateDatabaseResponse_QNAME, GetDateDatabaseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateSyncHourBranch }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateSyncHourBranch }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updateSyncHourBranch")
    public JAXBElement<UpdateSyncHourBranch> createUpdateSyncHourBranch(UpdateSyncHourBranch value) {
        return new JAXBElement<UpdateSyncHourBranch>(_UpdateSyncHourBranch_QNAME, UpdateSyncHourBranch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateSyncHourBranchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateSyncHourBranchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updateSyncHourBranchResponse")
    public JAXBElement<UpdateSyncHourBranchResponse> createUpdateSyncHourBranchResponse(UpdateSyncHourBranchResponse value) {
        return new JAXBElement<UpdateSyncHourBranchResponse>(_UpdateSyncHourBranchResponse_QNAME, UpdateSyncHourBranchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTotalPointOfSwapCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTotalPointOfSwapCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updateTotalPointOfSwapCustomer")
    public JAXBElement<UpdateTotalPointOfSwapCustomer> createUpdateTotalPointOfSwapCustomer(UpdateTotalPointOfSwapCustomer value) {
        return new JAXBElement<UpdateTotalPointOfSwapCustomer>(_UpdateTotalPointOfSwapCustomer_QNAME, UpdateTotalPointOfSwapCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTotalPointOfSwapCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTotalPointOfSwapCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updateTotalPointOfSwapCustomerResponse")
    public JAXBElement<UpdateTotalPointOfSwapCustomerResponse> createUpdateTotalPointOfSwapCustomerResponse(UpdateTotalPointOfSwapCustomerResponse value) {
        return new JAXBElement<UpdateTotalPointOfSwapCustomerResponse>(_UpdateTotalPointOfSwapCustomerResponse_QNAME, UpdateTotalPointOfSwapCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKeyPro }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKeyPro }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKeyPro")
    public JAXBElement<ActiveKeyPro> createActiveKeyPro(ActiveKeyPro value) {
        return new JAXBElement<ActiveKeyPro>(_ActiveKeyPro_QNAME, ActiveKeyPro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKeyProResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKeyProResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKeyProResponse")
    public JAXBElement<ActiveKeyProResponse> createActiveKeyProResponse(ActiveKeyProResponse value) {
        return new JAXBElement<ActiveKeyProResponse>(_ActiveKeyProResponse_QNAME, ActiveKeyProResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountTransaction }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CountTransaction }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "countTransaction")
    public JAXBElement<CountTransaction> createCountTransaction(CountTransaction value) {
        return new JAXBElement<CountTransaction>(_CountTransaction_QNAME, CountTransaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountTransactionResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CountTransactionResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "countTransactionResponse")
    public JAXBElement<CountTransactionResponse> createCountTransactionResponse(CountTransactionResponse value) {
        return new JAXBElement<CountTransactionResponse>(_CountTransactionResponse_QNAME, CountTransactionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNumRowConfigPos }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetNumRowConfigPos }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getNumRowConfigPos")
    public JAXBElement<GetNumRowConfigPos> createGetNumRowConfigPos(GetNumRowConfigPos value) {
        return new JAXBElement<GetNumRowConfigPos>(_GetNumRowConfigPos_QNAME, GetNumRowConfigPos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNumRowConfigPosResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetNumRowConfigPosResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getNumRowConfigPosResponse")
    public JAXBElement<GetNumRowConfigPosResponse> createGetNumRowConfigPosResponse(GetNumRowConfigPosResponse value) {
        return new JAXBElement<GetNumRowConfigPosResponse>(_GetNumRowConfigPosResponse_QNAME, GetNumRowConfigPosResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckCodeBranch }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckCodeBranch }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "checkCodeBranch")
    public JAXBElement<CheckCodeBranch> createCheckCodeBranch(CheckCodeBranch value) {
        return new JAXBElement<CheckCodeBranch>(_CheckCodeBranch_QNAME, CheckCodeBranch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckCodeBranchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckCodeBranchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "checkCodeBranchResponse")
    public JAXBElement<CheckCodeBranchResponse> createCheckCodeBranchResponse(CheckCodeBranchResponse value) {
        return new JAXBElement<CheckCodeBranchResponse>(_CheckCodeBranchResponse_QNAME, CheckCodeBranchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNumRowConfig }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetNumRowConfig }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getNumRowConfig")
    public JAXBElement<GetNumRowConfig> createGetNumRowConfig(GetNumRowConfig value) {
        return new JAXBElement<GetNumRowConfig>(_GetNumRowConfig_QNAME, GetNumRowConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNumRowConfigResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetNumRowConfigResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getNumRowConfigResponse")
    public JAXBElement<GetNumRowConfigResponse> createGetNumRowConfigResponse(GetNumRowConfigResponse value) {
        return new JAXBElement<GetNumRowConfigResponse>(_GetNumRowConfigResponse_QNAME, GetNumRowConfigResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKeyNew }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKeyNew }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKeyNew")
    public JAXBElement<ActiveKeyNew> createActiveKeyNew(ActiveKeyNew value) {
        return new JAXBElement<ActiveKeyNew>(_ActiveKeyNew_QNAME, ActiveKeyNew.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKeyNewResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKeyNewResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKeyNewResponse")
    public JAXBElement<ActiveKeyNewResponse> createActiveKeyNewResponse(ActiveKeyNewResponse value) {
        return new JAXBElement<ActiveKeyNewResponse>(_ActiveKeyNewResponse_QNAME, ActiveKeyNewResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseKeyByShortKey }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseKeyByShortKey }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getLicenseKeyByShortKey")
    public JAXBElement<GetLicenseKeyByShortKey> createGetLicenseKeyByShortKey(GetLicenseKeyByShortKey value) {
        return new JAXBElement<GetLicenseKeyByShortKey>(_GetLicenseKeyByShortKey_QNAME, GetLicenseKeyByShortKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseKeyByShortKeyResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseKeyByShortKeyResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getLicenseKeyByShortKeyResponse")
    public JAXBElement<GetLicenseKeyByShortKeyResponse> createGetLicenseKeyByShortKeyResponse(GetLicenseKeyByShortKeyResponse value) {
        return new JAXBElement<GetLicenseKeyByShortKeyResponse>(_GetLicenseKeyByShortKeyResponse_QNAME, GetLicenseKeyByShortKeyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountCategory }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CountCategory }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "countCategory")
    public JAXBElement<CountCategory> createCountCategory(CountCategory value) {
        return new JAXBElement<CountCategory>(_CountCategory_QNAME, CountCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountCategoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CountCategoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "countCategoryResponse")
    public JAXBElement<CountCategoryResponse> createCountCategoryResponse(CountCategoryResponse value) {
        return new JAXBElement<CountCategoryResponse>(_CountCategoryResponse_QNAME, CountCategoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPointOfCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPointOfCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getPointOfCustomer")
    public JAXBElement<GetPointOfCustomer> createGetPointOfCustomer(GetPointOfCustomer value) {
        return new JAXBElement<GetPointOfCustomer>(_GetPointOfCustomer_QNAME, GetPointOfCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPointOfCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPointOfCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getPointOfCustomerResponse")
    public JAXBElement<GetPointOfCustomerResponse> createGetPointOfCustomerResponse(GetPointOfCustomerResponse value) {
        return new JAXBElement<GetPointOfCustomerResponse>(_GetPointOfCustomerResponse_QNAME, GetPointOfCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseKey }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseKey }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getLicenseKey")
    public JAXBElement<GetLicenseKey> createGetLicenseKey(GetLicenseKey value) {
        return new JAXBElement<GetLicenseKey>(_GetLicenseKey_QNAME, GetLicenseKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseKeyResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseKeyResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "getLicenseKeyResponse")
    public JAXBElement<GetLicenseKeyResponse> createGetLicenseKeyResponse(GetLicenseKeyResponse value) {
        return new JAXBElement<GetLicenseKeyResponse>(_GetLicenseKeyResponse_QNAME, GetLicenseKeyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckSyncShop }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckSyncShop }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "checkSyncShop")
    public JAXBElement<CheckSyncShop> createCheckSyncShop(CheckSyncShop value) {
        return new JAXBElement<CheckSyncShop>(_CheckSyncShop_QNAME, CheckSyncShop.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckSyncShopResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckSyncShopResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "checkSyncShopResponse")
    public JAXBElement<CheckSyncShopResponse> createCheckSyncShopResponse(CheckSyncShopResponse value) {
        return new JAXBElement<CheckSyncShopResponse>(_CheckSyncShopResponse_QNAME, CheckSyncShopResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCodeBranch }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateCodeBranch }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updateCodeBranch")
    public JAXBElement<UpdateCodeBranch> createUpdateCodeBranch(UpdateCodeBranch value) {
        return new JAXBElement<UpdateCodeBranch>(_UpdateCodeBranch_QNAME, UpdateCodeBranch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCodeBranchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateCodeBranchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updateCodeBranchResponse")
    public JAXBElement<UpdateCodeBranchResponse> createUpdateCodeBranchResponse(UpdateCodeBranchResponse value) {
        return new JAXBElement<UpdateCodeBranchResponse>(_UpdateCodeBranchResponse_QNAME, UpdateCodeBranchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePointOfSwapCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdatePointOfSwapCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updatePointOfSwapCustomer")
    public JAXBElement<UpdatePointOfSwapCustomer> createUpdatePointOfSwapCustomer(UpdatePointOfSwapCustomer value) {
        return new JAXBElement<UpdatePointOfSwapCustomer>(_UpdatePointOfSwapCustomer_QNAME, UpdatePointOfSwapCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePointOfSwapCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdatePointOfSwapCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "updatePointOfSwapCustomerResponse")
    public JAXBElement<UpdatePointOfSwapCustomerResponse> createUpdatePointOfSwapCustomerResponse(UpdatePointOfSwapCustomerResponse value) {
        return new JAXBElement<UpdatePointOfSwapCustomerResponse>(_UpdatePointOfSwapCustomerResponse_QNAME, UpdatePointOfSwapCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKey }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKey }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKey")
    public JAXBElement<ActiveKey> createActiveKey(ActiveKey value) {
        return new JAXBElement<ActiveKey>(_ActiveKey_QNAME, ActiveKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveKeyResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActiveKeyResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.client.pos.shopy.viettel.com/", name = "activeKeyResponse")
    public JAXBElement<ActiveKeyResponse> createActiveKeyResponse(ActiveKeyResponse value) {
        return new JAXBElement<ActiveKeyResponse>(_ActiveKeyResponse_QNAME, ActiveKeyResponse.class, null, value);
    }

}
