//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.14 at 03:37:10 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.client.pos.shopy.viettel.com/")
package ru.demo.pnpscada.soap.bindings;
